/**
 * Al Quran Al Kareem Recitation by Various Qaris القرآن الكريم
 * @author         : Muddassir Ahmed Khan
 * Contact         : muddassir.ahmed235@gmail.com
 * Github Username : muddassir235
 *
 * SuvarData.kt
 *
 * This Kotlin file has the basic model of the Quran (SurahInfo name in arabic and english, the index,
 * Place of revelation).
 */
package com.muddassir.tilawa

/* Functional programming. Test driven development */
private val suvarData = linkedMapOf(
    "ٱلْفَاتِحَة"   to Pair("The Opening",                       "makki" ),
    "البَقَرة"    to Pair("The Cow",                           "madani"),
    "آل عِمران"  to Pair("The House of Imran",                "madani"),
    "النِّســاء"  to Pair("Women",                             "madani"),
    "المَـائِدة"  to Pair("The Table Spread",                  "madani"),
    "الأنْعـامِ"   to Pair("The Cattle",                        "makki" ),
    "الأعراف"    to Pair("The Heights",                       "makki" ),
    "الأنْفـال"   to Pair("The Spoils",                        "madani"),
    "التـَّوْبَة"   to Pair("The Repentance",                    "madani"),
    "يُونُس"      to Pair("Jonah",                             "makki" ),
    "هُود"       to Pair("Hud",                               "makki" ),
    "يُوسُف"      to Pair("Joseph",                            "makki" ),
    "الرَّعد"     to Pair("The Thunder",                       "madani"),
    "اِبراهيم"   to Pair("Abraham",                           "makki" ),
    "الحِجْر"     to Pair("The Rocky Tract",                   "makki" ),
    "النًّحل"     to Pair("The Bee",                           "makki" ),
    "الاِسْرآء"    to Pair("The Night Journey",                 "makki" ),
    "الكَهْف"     to Pair("The Cave",                          "makki" ),
    "مَريَم"      to Pair("Mary",                              "makki" ),
    "طه"        to Pair("Ta Ha",                             "makki" ),
    "الأنْبيآء"   to Pair("The Prophets",                      "makki" ),
    "الحَجّ"      to Pair("The Pilgrimage",                    "madani"),
    "المؤمِنون"  to Pair("The Believers",                     "makki" ),
    "النّور"     to Pair("The Light",                         "madani"),
    "الفُرقان"   to Pair("The Criterion",                     "makki" ),
    "الشُّـعَراء"  to Pair("THe Poets",                         "makki" ),
    "النَّـمْل"    to Pair("The Ant",                           "makki" ),
    "القَصَصِ"     to Pair("The Stories",                       "makki" ),
    "العَنْـكَبُوت" to Pair("The Spider",                        "makki" ),
    "الرُّوم"     to Pair("The Romans",                        "makki" ),
    "لُقْمان"     to Pair("Luqman",                            "makki" ),
    "السَّـجْدة"   to Pair("The Prostration",                   "makki" ),
    "الأحزاب"    to Pair("The Combined Forces",               "madani"),
    "ســَبَأ"     to Pair("Sheba",                             "makki" ),
    "فاطِر"      to Pair("Originator",                        "makki" ),
    "يــس"      to Pair("Ya Seen",                           "makki" ),
    "الصّــافّات" to Pair("Those Who Set the Ranks",           "makki" ),
    "ص"         to Pair("The Letter \"Saad\"",               "makki" ),
    "الزُّمَر"     to Pair("The Companies",                     "makki" ),
    "المُؤْمِنِ"    to Pair("The Believer",                      "makki" ),
    "فُصِّلَتِ"      to Pair("Explained in Detail",               "makki" ),
    "الشُّوری"    to Pair("The Consultation",                  "makki" ),
    "الزُّخْرُف"    to Pair("The Ornaments to Gold",             "makki" ),
    "الدُّخان"    to Pair("The Smoke",                         "makki" ),
    "الجاثِية"   to Pair("The Crouching",                     "makki" ),
    "الأحقاف"    to Pair("The Wind-Curved Sand-Dunes",        "makki" ),
    "مُحَمّد"      to Pair("Muhammad",                          "madani"),
    "الفَتْح"     to Pair("The Victory",                       "madani"),
    "الحُجُرات"   to Pair("The Apartments",                    "madani"),
    "ق"         to Pair("The Letter \"Qaf\"",                "makki" ),
    "الذ ّارِيات" to Pair("The Winnowing Winds",               "makki" ),
    "الطُّور"     to Pair("The Mount",                         "makki" ),
    "النَّجْم"     to Pair("The Star",                          "makki" ),
    "القَمَر"     to Pair("The Moon",                          "makki" ),
    "الرَّحمن"    to Pair("The Merciful",                      "madani"),
    "الواقِعَة"   to Pair("The Inevitable",                    "makki" ),
    "الحَديد"    to Pair("The Iron",                          "madani"),
    "المُجادَلة"  to Pair("The Pleading Woman",                "madani"),
    "الحَشْر"     to Pair("The Exile",                         "madani"),
    "المُمتَحَنة"  to Pair("She that is to be Examined",        "madani"),
    "الصَّف"      to Pair("The Ranks",                         "madani"),
    "الجُّمُعة"    to Pair("The Congregation, Friday",          "madani"),
    "المُنافِقُون" to Pair("The Hypocrites",                    "madani"),
    "التَّغابُن"   to Pair("The Mutual Disillusion",            "madani"),
    "الطَّلاق"     to Pair("The Divorce",                       "madani"),
    "التَّحْريم"   to Pair("The Prohibition",                   "madani"),
    "المُلْك"     to Pair("The Kingdom",                       "makki" ),
    "القَلـََم"    to Pair("The Pen",                           "makki" ),
    "الحَاقّـَة"   to Pair("The Indubitable",                   "makki" ),
    "المَعارِج"   to Pair("The Ascending Stairways",           "makki" ),
    "نُوح"       to Pair("Noah",                              "makki" ),
    "الجِنّ"      to Pair("The Jinn",                          "makki" ),
    "المُزَّمّـِل"   to Pair("The Enshrouded One",                "makki" ),
    "المُدَّثــِّر"  to Pair("The Clocked One",                   "makki" ),
    "القِيامَة"   to Pair("The Resurrection",                  "makki" ),
    "الدَّهر"     to Pair("The Time",                          "madani"),
    "المُرسَلات"   to Pair("The Emissaries",                    "makki" ),
    "النـَّبأ"    to Pair("The Tiding",                        "makki" ),
    "النـّازِعات" to Pair("Those who Drag Forth",              "makki" ),
    "عَبَس"       to Pair("He Frowned",                        "makki" ),
    "التـَّكْوير"  to Pair("The Overthrowing",                  "makki" ),
    "الإنفِطار"   to Pair("The Cleaving",                      "makki" ),
    "المُطـَفِّفين" to Pair("The Stinters",                      "makki" ),
    "الإنشِقاق"   to Pair("The Sundering",                     "makki" ),
    "البُروج"    to Pair("The Mansions of Stars",             "makki" ),
    "الطّارق"    to Pair("The Night Comer",                   "makki" ),
    "الأعلی"     to Pair("The Most High",                     "makki" ),
    "الغاشِيَة"   to Pair("The Overwhelming",                  "makki" ),
    "الفَجْر"     to Pair("The Dawn",                          "makki" ),
    "البَـلـَد"   to Pair("The City",                          "makki" ),
    "الشــَّمْس"   to Pair("The Sun",                           "makki" ),
    "اللـَّيل"    to Pair("The Night",                         "makki" ),
    "الضُّحی"     to Pair("The Morning Hours",                 "makki" ),
    "الإنشـِراح"  to Pair("The Relief",                        "makki" ),
    "التـِّين"    to Pair("The Fig",                           "makki" ),
    "العَلـَق"    to Pair("The Blood-clot",                    "makki" ),
    "القـَدر"    to Pair("The Power",                         "makki" ),
    "البَيِّنَة"    to Pair("The Clear Proof",                   "madani"),
    "الزِّلزال"   to Pair("The Earthquake",                    "madani"),
    "العـَاديات" to Pair("The Courser",                       "makki" ),
    "القارِعَة"   to Pair("The Calamity",                      "makki" ),
    "التَكاثـُر"  to Pair("The Rivalry (In Worldly Increase)", "makki" ),
    "العَصْر"     to Pair("The Declining Day",                 "makki" ),
    "الهُمَزَة"    to Pair("The Backbiter",                     "makki" ),
    "الفيل"     to Pair("The Elephant",                      "makki" ),
    "قـُرَيْش"     to Pair("Quraysh",                           "makki" ),
    "الماعُون"   to Pair("The Small Kindnesses",              "makki" ),
    "الكـَوْثَر"   to Pair("The Abundance",                     "makki" ),
    "الكافِرون"  to Pair("The Disbelievers",                  "makki" ),
    "النـَّصر"    to Pair("The Divine Aid",                    "madani"),
    "تَبَّت"       to Pair("The Palm Fiber",                    "makki" ),
    "الإخـْلاص"    to Pair("The Sincerity",                     "makki" ),
    "الفـَلَق"    to Pair("The Daybreak",                      "makki" ),
    "النـَّاس"    to Pair("The Mankind",                       "makki" )
)

/* Suvar is plural of Surah in Arabic */
val SUVAR_INFO: Array<SurahInfo> = Array(114) { i -> SurahInfo(
        number = i,
        arabicName = suvarData.keys.elementAt(i),
        englishName = suvarData.values.elementAt(i).first,
        makkiOrMadani = suvarData.values.elementAt(i).second
    )
}